### ISSUE TITLE
Add Config File

### ISSUE THREAD

**Issue by letrad** [letrad/QuirkWM#3]
Work on adding a config file. Perhaps TOML? This might be the kind of style / syntax to go for:
```toml
[window.properities]
border       = "3px"
border-color = "#123123"
gap          = "5px"

[super+T]
exec kitty

[super+AK_LEFT]
focus_previous_window
```
